rootProject.name = "git-kata-exercises"
include(
    ":101-local-amend-commit",
    ":102-local-commit-changes",
    ":103-local-undo-last-commit",
    ":104-local-rebase-onto-main",
    ":105-local-rebase-with-conflicts",
    ":106-local-interactive-rebase-reorder-commits",
    ":107-local-interactive-rebase-squash-commits",
    ":108-local-interactive-rebase-reword-commits",
    ":109-local-interactive-rebase-edit-commits",
    ":110-local-interactive-rebase-split-commits",
    ":111-local-interactive-rebase-delete-commits",
    ":201-remote-amend-commit",
    ":202-remote-undo-last-commit",
    ":203-remote-rebase-onto-main",
    ":204-remote-rebase-with-teammates",
    ":205-remote-interactive-rebase",
    ":206-remote-cherry-pick-commit-on-main",
    ":301-remote-advanced-interactive-rebase",
    ":exercise"
)
